python3 test.py --video_path './tests/01.mp4'
python3 test.py --video_path './tests/03.mp4'
python3 test.py --video_path './tests/05.mp4'
python3 test.py --video_path './tests/07.mp4'
python3 test.py --video_path './tests/09.mp4'